[package]
name = "uf2"
version = "0.1.0"
authors = ["Jacob Rosenthal <@jacobrosenthal>"]
edition = "2018"
description = "Microsoft HID Flashing Format"
repository = "https://github.com/jacobrosenthal/uf2-rs"
keywords = ["hid", "pygamer", "flash"]


[lib]
name = "uf2"
path = "src/lib.rs"

[[bin]]
name = "uf2"
path = "src/bin.rs"


[patch.crates-io]
scroll = { git = 'https://github.com/m4b/scroll', features = ["derive"] }


[dependencies]
structopt = { version = "0.3"}
hidapi = "0.5.2"
scroll = { version = "0.10.0", features = ["derive"] }
crc = "1.9.0"


