[package]
name = "dfu"
version = "0.1.0"
authors = ["Jacob Rosenthal <jacobrosenthal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[patch.crates-io]
scroll = { git = 'https://github.com/m4b/scroll', features = ["derive"] }
crc = { git = 'https://github.com/mrhooray/crc-rs' }


[dependencies]
hidapi = "0.5.2"
scroll = { version = "0.10.0", features = ["derive"] }
crc = "1.0.0"
byteorder = "1.3.2"


